=== kong-ling/scripts/xml/sslRoute.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.w3school.com.cn"
xmlns="http://www.w3school.com.cn"
elementFormDefault="qualified">

<xs:element name="sslRoute">
    <xs:complexType>
      <xs:sequence>
	    <xs:element name="row" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="entry" type="xs:string"
              minOccurs="3" maxOccurs="3"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
</xs:element>

</xs:schema>

=== kong-ling/scripts/xml/sslRoute.xml
<?xml version="1.0"?>
<sslRoute
    xmlns="http://www.w3school.com.cn"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.w3school.com.cn sslRoute.xsd">
    <row><entry>SSL24ML0</entry><entry>CAM1_SNK</entry><entry>INO_SRC</entry></row> 
    <row><entry>SSL32ML0</entry><entry>SSL32NOC_SNK</entry><entry>SSL2AHB1_SRC</entry></row> 
    <row><entry>SSL24ML1</entry><entry>CAM1_SNK</entry><entry>INO_SRC</entry></row> 
    <row><entry>SSL32ML1</entry><entry>SSL32NOC_SNK</entry><entry>SSL2AHB1_SRC</entry></row> 
    <row><entry>SSL24ML0</entry><entry>CAM1_SNK</entry><entry>INO_SRC</entry></row> 
    <row><entry>SSL32ML0</entry><entry>SSL32NOC_SNK</entry><entry>SSL2AHB1_SRC</entry></row> 
</sslRoute>
